### ISSUE TITLE
[Q6] Discrétisation du laplacien

### ISSUE THREAD

**Issue by tizot** [tizot/projet-scilab-map411#3]
Pour répondre à la première partie de la question 6, il faut approcher le laplacien. 
Pour que ça marche avec la suite du problème, il faut montrer ∆U = Ū - U.
Pour cela, on utilise les formules de Taylor :
 u(x+h,y) = u(x,y) + h ∂u + h^2/2 ∂^2u
et :
 u(x+h, y+h) = u(x,y) + ...
On trouve alors facilement deux expressions du laplacien : une avec des déplacements dans une seule direction, et une avec des déplacements "croisés". Le truc pour obtenir la valeur de ∆U qui va bien, c'est de faire la moyenne des deux expressions et de la diviser par 3. 
Pourquoi 3 ? ^^
Ou alors on doit trouver ∆U = 3(Ū - U) mais je ne suis pas convaincu que la suite des calculs corresponde à ce qui est demandé...

**Comment by NTag** [comment]
Mais Camille on s'en fout de ce vieux repo ^^
Le ven. 31 juil. 2015 à 08:58, Camille Masset notifications@github.com a
écrit :

**Comment by tizot** [comment]
Il restait une issue non close dans "Issues" sur GitHub (là où tu peux voir
toutes les issues de tes projets), donc ça m'énervait :p

Le ven. 31 juil. 2015 à 09:27, Basile Bruneau notifications@github.com a
écrit :
